apiVersion: v1
kind: Service
metadata:
  name: ban-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ban-app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ban-app
  namespace: default
  labels:
    app: ban-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ban-app
  template:
    metadata:
      labels:
        app: ban-app
    spec:
      containers:
      - name: ban-app
        image: eu.gcr.io/ban-app/ban-app:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: ban-app
              key: connection-string
        - name: OXFORD_APP_ID
          valueFrom:
            secretKeyRef:
              name: ban-app
              key: oxford-app-id
        - name: OXFORD_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: ban-app
              key: oxford-app-secret
---