apiVersion: v1
kind: Service
metadata:
  name: banapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: banapp
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: banapp
  namespace: default
  labels:
    app: banapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banapp
  template:
    metadata:
      labels:
        app: banapp
    spec:
      containers:
      - name: banapp
        image: gcr.io/banapp/banapp:${CIRCLE_SHA1}
        imagePullPolicy: Always
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: banapp
              key: connection-string
        - name: OXFORD_APP_ID
          valueFrom:
            secretKeyRef:
              name: banapp
              key: oxford-app-id
        - name: OXFORD_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: banapp
              key: oxford-app-secret
---