# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.
      - image: mongo:3.4.4-jessie
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run: make image
      - run: make release

workflows:
  version: 2
  release:
      jobs:
        - test
        - build:
            requires:
              - test
            filters:
              brances:
                only: master
          