# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8
        environment:
            MONGODB_URL: mongodb://localhost:27017/ban-app
      - image: circleci/mongo
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run:
          name: Waiting for Mongo to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mongo && exit 1
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run: make image
      - run: make release
      - run: make deploy

workflows:
  version: 2
  release:
    jobs:
      - test
      - build:
          requires:
            - test