# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
            MONGODB_URL: mongodb://localhost:27017/ban-app
      - image: circleci/mongo
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run:
          name: Waiting for Mongo to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mongo && exit 1
      - run:
          name: Test
          command: make test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: | 
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
      - run:
          name: Install binaries
          command: apt-get install -qq -y make
      - setup_remote_docker
      - run: 
          name: Create Docker image
          command: make image
      - run:
          name: Push Docker image
          command: make release
      - run:
          name: Deploy to Kubernetes
          command: make deploy

workflows:
  version: 2
  release:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master