# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          MONGODB_URL: mongodb://localhost:27017/ban-app
      - image: circleci/mongo
    working_directory: /go/src/ban-app
    steps:
      - checkout
      - run:
          name: Waiting for Mongo to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mongo && exit 1
      - run:
          name: Test
          command: go test ./... -v
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup deps
          command: apt-get install -qq -y gettext
      - run:
          name: Setup Google Cloud SDK
          command: | 
            echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ban-app
            gcloud --quiet config set compute/zone europe-west2-a
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run: 
          name: Create Docker image
          command: docker build -t ban-app:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image
          command: |
            docker tag ban-app:${CIRCLE_SHA1} gcr.io/ban-app/ban-app:${CIRCLE_SHA1}
            docker push gcr.io/ban-app/ban-app:${CIRCLE_SHA1}
      - run:
          name: Deploy to Kubernetes
          command: |
            envsubst < env/k8s/app.yml > /tmp/app.yml
            kubectl apply -f /tmp/app.yml
            kubectl rollout status -w deployment/ban-app

workflows:
  version: 2
  release-staging:
    jobs:
      - test:
          filters:
            branches:
              only: develop
          context: ban-app-staging
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
          context: ban-app-staging
  release-prod:
    jobs:
      - test:
          filters:
            branches:
              only: master
          context: ban-app-prod
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
          context: ban-app-prod